### ISSUE TITLE
Auto-adding empty synonym when using iPad keyboard

### ISSUE THREAD

**Issue by sushigoose** [davidsansome/tsurukame#166]
Sometimes when typing with my Bluetooth connected keyboard, the app will skip allowing me to input a correct answer and when I explore the item being reviewed, it now has an empty synonym. For instance, I have the reviews set up to test on reading and then meaning:
1. Incorrectly answer reading.
2. Quickly skips the meaning and then goes onto the next item.
3. Reviewing the item on the webpage has an empty synonym.
It’s a little tricky to reproduce, but seems to be correspond to typing too quickly.

**Comment by indirect** [comment]
I think I've run into this myself, and I think it happens when the letter you are typing happens to include "s", which is the hotkey to add a synonym on the "review" screen. I was thinking the solution might be to make the shortcuts also require the command key? Like, ⌘S instead of just S. That way randomly pushing letters never gets you results like adding a synonym or marking a wrong answer correct. I'm not sure what the actual underlying bug is, though.

**Comment by sushigoose** [comment]
Ah! That makes a lot of sense. I've tried to teach myself to slow down after getting it wrong. I really should be slowing down and reviewing my error. Yes, I think an extra step would be nice to add a synonym. It's also randomly read the reading to me when I've been a bit too hyper on the keyboard.
