### ISSUE TITLE
Feature suggestion: show all readings in kanji

### ISSUE THREAD

**Issue by timmy-lee** [davidsansome/tsurukame#230]
Something like this when looking up kanji:
![image](https://user-images.githubusercontent.com/20361890/70157348-477de980-166a-11ea-8e94-3189231b2964.png)

It looks like this only appears when looking up specific kanji and not in the lessons. So as far as this request is concerned, having that feature parity would be nice, but having it appear in the lessons would be even nicer.

**Comment by timmy-lee** [comment]
@davidsansome If this sounds like a feature that you think would be a nice addition, I'd be happy to try tackling it and familiarizing myself with this project to help with future contributions. 😄

**Comment by turtlemaster19** [comment]
While I am not him, I was contemplating this while opening #218. Hopefully this actually is implemented, (but maybe not in Lessons) as this is standard WK (and AlliCrab) behavior

**Comment by davidsansome** [comment]
WaniKani marks these non-primary Kanji readings as wrong, which is why they're not shown during lessons so you don't learn incorrect answers.
I'd be happy to show these other readings outside of lessons.  We could maybe show them during lessons as well if we made it very clear which one is the "correct" Kanji reading, and that the other one is only being shown for information purposes and not as part of the lesson.

The code that hides non-primary readings is here: https://github.com/davidsansome/tsurukame/blob/master/ios/SubjectDetailsView.swift#L74 and https://github.com/davidsansome/tsurukame/blob/master/ios/SubjectDetailsView.swift#L142.  You'd probably need to add a showNonPrimaryReadings bool to SubjectDetailsViewController (https://github.com/davidsansome/tsurukame/blob/master/ios/SubjectDetailsViewController.m#L43) which we can set to false in lessons and true elsewhere.

Do you want to have a go at implementing that?  I can answer any more questions if you have them!

**Comment by timmy-lee** [comment]
By enabling the primary readings in the way you mentioned, I get something like this:
![image](https://user-images.githubusercontent.com/20361890/70448096-b2596700-1a54-11ea-9c9f-edf917c04d62.png)

But I was thinking more of something like this (the readings themselves haven't been sorted yet):
![image](https://user-images.githubusercontent.com/20361890/70448379-21cf5680-1a55-11ea-8452-f4efb0befab5.png)
While having the non-primary reading(s) in light gray text or having the primary reading in bold text. What do you think @davidsansome?

**Comment by sciencemanx** [comment]
another important note onyomi should be katakana and kunyomi + nanori should be in hiragana. Probably the "suggested" reading should be at the top

**Comment by sciencemanx** [comment]
another thing to consider is how much vertical space is consumed from having a section for each reading

**Comment by turtlemaster19** [comment]
I think that non-primary readings should still be shown in a different shade to tell them apart.
