### ISSUE TITLE
Reviews don’t sync

### ISSUE THREAD

**Issue by rogovich** [davidsansome/tsurukame#235]
Hi! First, the app is amazing. However, my reviews and lessons do not sync neither to wanikani website nor to Tsurukame app on another device (iPad and iPhone). Doing reviews online. If I log out app, when I log in back I see the same number of reviews that wanikani shows.  E.g. I had 200 reviews, I did 100 in Tsurukame, it had never synced, I logged out, logged in and see the same 200 reviews.

**Comment by turtlemaster19** [comment]
Are there any queued updates?

**Comment by rogovich** [comment]
225 seems something like this. No updates queued. Just yesterday installed the app for the first time on both devices, similar behavior. Tried today and it is the same. Reviews are local and do not sync.

**Comment by turtlemaster19** [comment]
@rogovich Could this be #184 or related to it?

**Comment by turtlemaster19** [comment]
This issue is still occurring. Reported today at https://community.wanikani.com/t/ios-tsurukame-native-app-with-offline-lessons-and-reviews/30635/530

> For some reason, every time I complete a review session, the number on the app’s homepage reverts back after the refresh.

I’ve tried to confirm with the website through the browser but the numbers aren’t matching up.

I tried reinstalling the app, but it still happens.

**Comment by turtlemaster19** [comment]
This issue is still occurring. Reported today at https://community.wanikani.com/t/ios-tsurukame-native-app-with-offline-lessons-and-reviews/30635/530

>For some reason, every time I complete a review session, the number on the app’s homepage reverts back after the refresh.
I’ve tried to confirm with the website through the browser but the numbers aren’t matching up.
I tried reinstalling the app, but it still happens.

**Comment by mzsanford** [comment]
@rogovich do you have a Mac? If so could you view the logs on the phone ([instructions for using Console.app to view logs](http://osxdaily.com/2018/07/12/how-view-ios-logs-on-mac/))? It would be most helpful if you (diagram below):

  1. Select your phone - this will display your phone logs on the right hand side
  2. Search for "tsurukame" - type it in the box and hit `enter`. It will probably blank out the right hand side
  3. View output - Open Tsurukame on your phone and do a pull-to-refresh. You should see new messages start to appear on the right hand side. Then do some lessons or reviews, something that isn't working correctly. Try to reproduce it without adding too much else since I'll have to manually read these line-by-line.
  4. Save the output - Click the save button and save this search to a file. Post the file here and I'll see if I can find the root cause.

![Console.app visual aid](https://user-images.githubusercontent.com/33917/72913259-c0580400-3cf1-11ea-94de-e79f22cdf9b6.png)

**Comment by turtlemaster19** [comment]
See #277
