### ISSUE TITLE
Allow users to make notes on meanings

### ISSUE THREAD

**Issue by Goombario** [davidsansome/tsurukame#27]
I would like to be able to see the notes I have on meanings and create new ones.

**Comment by pascaldisse** [comment]
I think this is a very important feature. Sometimes the given mnemonics can be quite terrible, so I have created quite a few myself. For now, it would be great to be at least able to read them.
I dug a little bit through your code to see if I could implement it myself but objective-c scares me, haha. I think I will stick to swift for now.

**Comment by dysnomian** [comment]
This would be a very helpful feature for me as well. I'm currently looking through the code, and would love some guidance on how to implement it. Is there a discussion page or IRC for this?

**Comment by turtlemaster19** [comment]
@pascaldisse That is exactly the reason #57 is open - because Objective-C throws off possible contributors.

**Comment by dambros** [comment]
+1 for the notes. It is fundamental to have this feature both for meaning and reading.

**Comment by turtlemaster19** [comment]
To get from the API, unfortunately, it's not part of the data endpoint, but rather a separate study material object: https://docs.api.wanikani.com/20170710/#study-materials
This means we're currently not retrieving them. To implement this, we would probably need to make a commit like d095f05 modifying the Go code, then modify `proto/wanikani.proto` before we could even touch the Swift code at `SubjectDetailsView.swift`. The one thing we wouldn't need is Objective-C!

**Comment by turtlemaster19** [comment]
All that will need to be done is modify `SubjectDetailsView.swift`. I might create a PR soon!

**Comment by turtlemaster19** [comment]
@pascaldisse @dysnomian In 2dd5406425408d88d6c72ad997167d2145ce2234, `SubjectDetailsView` was converted to Swift. I have created a PR, which if passing and functional, would implement the bare minimum of viewing existing notes. This may be useful if either of you are attempting to implement creating notes.

**Comment by dysnomian** [comment]
Hooray! Thank you for implementing this, @turtlemaster19!

**Comment by geerk** [comment]
Hi @UInt2048 , thanks for implementing this feature!
It seems there is a bug in displaying notes. I checked the API and it returns both meaning_note and reading_note correctly, that is why I believe the bug is in the app. Below I will try to describe more about it:

1. Add "Meaning Note" **only** via Wanikani => Tsurukame displays it as "MEANING NOTE" (All good here)
2. Add "Reading Note" **only** via Wanikani => Tsurukame displays it as "MEANING NOTE" (It should probably display it as "READING NOTE")
3. Add **both** "Meaning Note" and "Reading Note" via Wanikani => Tsurukame ignores "Meaning note" from Wanikani and displays the content of "Reading Note" from Waniknai under "MEANING NOTE" section in the app (It should probably display both notes)

Hope this will help to fix this bug. Unfortunately I am not familiar with iOS development so cannot fix it myself :(

**Comment by UInt2048** [comment]
@geerk Thanks for the feedback. I will try to look into the cause of the problem with this new information. I am aware it is inside the app, see my above comment in this issue (and in duplicate #361)
