### ISSUE TITLE
Automatic keyboard switching

### ISSUE THREAD

**Issue by dmikhalsky** [davidsansome/tsurukame#275]
I do believe it is a very useful feature but I am struggling to understand the way it is implmented now.

"Big" (Web) Wanikani has IME built-in so does Tsurukame, so there is no need to use JP keyboard in the app. I don't switch keyboards, I just set keyboard as English and it provides proper input for Meaning (directly) and for Reading (via automatic conversion to Japanese)

If automatic switching is set to ON, then the app just starts switching back and forth between JP and EN keyboards. Does anyone need JP keyboard while using the app?

However, as I said, keyboard switching is very useful 'cause I (for example) have 3 different keyboards installed (EN, JP and RU) and it would be very nice if Tsurukame could switch to EN keyboard automatically

**Comment by turtlemaster19** [comment]
Yes, I use the Japanese keyboard in the app. I agree that it should be a three-way setting:
Off, English only, English and Japanese

Unfortunately, I am not that great with view controllers, so this wouldn't be an easy fix for me. For some other contributors, this wouldn't be too hard.

**Comment by dmikhalsky** [comment]
Got it. Happy that we are aligned. 
Just for reference: is there an advantage to use JP keyboard? May be I should start using it

**Comment by turtlemaster19** [comment]
I prefer it to roomaji and nn

**Comment by turtlemaster19** [comment]
I prefer it to roomaji and nn
Tofugu has an article about "how romaji can ruin your day": https://www.tofugu.com/japanese/romaji/

**Comment by mzsanford** [comment]
I don't have any analytics from Tsurukame to back this up but it is my assumption most users are using the standard romanji IME like Wanikani. I added the keyboard switching but left it disabled by default since that was my assumption. I believe the switching option exists for people who want to practice the kana keyboard as part of reviews (I always mistype つ in romanji for some reason. Not so with the kana keyboard).

The first edition of the switching code, when enabled via settings, was switching between JA and EN keyboards. That was reported as a bug in Issue https://github.com/davidsansome/tsurukame/issues/264. With the launch of PR https://github.com/davidsansome/tsurukame/pull/267 the switching feature, when enabled, will switch between Japanese and the user default keyboard. It sounds like the feature request here would be an option to lock it to EN app-wide, is that correct?

**Comment by bmironer** [comment]
Is there any way to identify and remember the selected keyboards separately for reading and meaning? Then go back to whatever keyboard I last used to enter the previous answer ?
I’m not sure there’s a specific API for that though. I believe keyboards are tied to textfield language.

**Comment by mzsanford** [comment]
@bmironer I found a way to save the state without finding and force-selecting a Japanese keyboard. As an example, assuming 3 keyboards {RU, EN, JA} with a system default of RU:

 1. Launch reviews, default keyboard=RU
 2. Presented "meaning" item
 3. Switch keyboard to EN
 4. Answer correctly (good job)
 5. Next item is a "reading" item, keyboard reverts to RU
 6. Switch keyboard to JA
 7. Answer correctly (you're on a roll)
 8. Next item is …
    * "meaning" - Keyboard changes to EN
    * "reading" - Keyboard stays JA

Posted PR https://github.com/davidsansome/tsurukame/pull/276
