### ISSUE TITLE
Weird UI bug when using pull-to-refresh

### ISSUE THREAD

**Issue by davidsansome** [davidsansome/tsurukame#28]
Screenshot here: https://discourse-cdn-sjc1.com/business5/uploads/wanikani_community/original/3X/e/c/ec91d11028cb1541e602b9ed90aa1f506cb2ea84.jpeg

**Comment by deadpadre** [comment]
I probably worded it a bit weird, it happens not during a pull-to-refresh attempt, but rather during scrolling in the opposite direction.

**Comment by patrickkelso** [comment]
I get this too. iPad Air 2 running IOS 11.3.

If I scroll to the bottom to see the level target diagrams (Which are super confusing at first) I get the blue bars.

I should note that this is in Landscape mode because I'm docked to a keyboard. In Portrait mode it still happens but everything is on the screen so I don't need to scroll.

The only way to clear it is to force quit the application and re-open.
