### ISSUE TITLE
Wrap-Up Doesn’t Ask Later

### ISSUE THREAD

**Issue by SomeGuyNamedDavid** [davidsansome/tsurukame#331]
Very minor quirk, if you “Ask Again Later” on the final item of a Wrap-Up, the review ends there anyway.

**Comment by turtlemaster19** [comment]
@SomeGuyNamedDavid That's intentional, and occurs no matter what item of the wrap-up it is, since you are trying to "wrap up," but you wanted it to ask again **later..**


For technical details, it's due to the fact that "ask again later" removes it from the queue, and a session is complete when the queue is clear, but no items are added to it during a wrap-up.

**Comment by SomeGuyNamedDavid** [comment]
The only concern I had was that you lose the half-review progress you had on that item in the process of doing so, but otherwise I agree that it's a perfectly valid way of handling the situation.
