### ISSUE TITLE
Bug: WaniKani data out of date

### ISSUE THREAD

**Issue by colepeters** [davidsansome/tsurukame#416]
It looks like Tsurukame’s data is out of date with the WaniKani website. I noticed when I got the answer for 工作 wrong on the app when using an answer I had learned on the website:

<img width='320' src='https://user-images.githubusercontent.com/1713932/97825663-f49b2080-1c84-11eb-989e-66aba3832846.jpeg' />
<img width='320' src='https://user-images.githubusercontent.com/1713932/97825666-f664e400-1c84-11eb-9748-fd7b3923f601.jpeg' />

Thanks for all your work on this app! 👍

**Comment by UInt2048** [comment]
@colepeters Click on the TestFlight link in the README. The App Store version hasn't been updated in a while, but the TestFlight version (which stays synced to the latest version on GitHub) already has this addressed.

Please close this issue, since we already have other issues such as #180 on this topic.

**Comment by colepeters** [comment]
Thank you!
