### ISSUE TITLE
No notifications since the Anki mode update

### ISSUE THREAD

**Issue by 310mc** [davidsansome/tsurukame#552]
Hello, thanks for developing this app, it's been doing wonders for me for many years!

I'm on iOS 15.4, and ever since I updated to the new version of Tsurukame that mentions it added Anki mode, it has stopped showing notifications or badges for me. It only starts to sync and show my reviews once I open the app itself. I'm not sure what changed. I tried re-installing, turning off and on notifications on app and on the settings, etc. and it's still not appearing.

**Comment by UInt2048** [comment]
I believe this is identical to #501

**Comment by 310mc** [comment]
I see, I suppose this is just a problem with iOS 15. Hopefully it fixes itself eventually!

**Comment by netnye** [comment]
I'm noticing this same problem since the most recent update. I do have iOS 15.4, but I don't think the problem began until updating the Tsurukame app. Also, other apps are still getting their badges notifications appropriately. I love this app so much, I hope this gets figured out soon, this functionality is one of the few things that has kept me consistent.

**Comment by lprunk** [comment]
Same here. Notifications stopped working after the last update. I've tried reinstalling and still no notifications. I'm on iOS 15.4, iPhone 12.
