### ISSUE TITLE
Incorrect answers marked as correct

### ISSUE THREAD

**Issue by mgehring** [davidsansome/tsurukame#554]
Since the recent update all incorrect answers are registered as correct and the cheat button text turned from “My answer was correct” to “ My answer was incorrect”, which is not even available when cheating is deactivated. This renders the app completely useless.

**Comment by UInt2048** [comment]
What settings do you have enabled? Does enabling & disabling settings related to partially correct answers & Anki mode help?

**Comment by mgehring** [comment]
I think this nightmare of an experience was actually caused by the new "pause" option. I disabled it and as far as I can tell the app works as before. 
The explanation of what "pause" does is apparently a little incomplete.

**Comment by UInt2048** [comment]
@mgehring That’s what I thought. The setting is supposed to allow you to mark an answer that was partially correct (e.g. “inqest” for 虫) wrong (e.g. you really meant “incest”)

It shouldn’t be messing with the behavior of actually incorrect answers, so that would be a pretty serious bug if it is.

**Comment by davidsansome** [comment]
Wow yeah that's exactly what it's doing - if the setting is enabled it marks every answer as correct: https://github.com/davidsansome/tsurukame/blob/master/ios/ReviewViewController.swift#L1047

I don't use this feature so I didn't realise how broken it was :(

I'm going to remove this feature for now - we can always add it back in later if we can implement it a bit better.

**Comment by UInt2048** [comment]
@davidsansome Sounds good, it clearly hasn’t been used since this wasn’t noticed in the testing period

**Comment by aaron-meyers** [comment]
@davidsansome @UInt2048 I've been using this feature for months and noticed in the TestFlights notes that it was pulled. Agreed that the setting is poorly named - I initially assumed that there was some logic for determining that an answer was "partially correct" (vs "completely wrong") but realized pretty quickly that it just triggers any time your answer is not an exact match. With this implementation it looks like this behaved the same as having "Exact match" and "Allow cheating" enabled but inverting the behavior of the continue > arrow (treated as "mark correct") and the left menu + option (renamed from "My answer was correct" to "My answer was incorrect"). I should be able to switch to using "Exact match" instead, will just have to make sure I don't tap > for correct responses...

I'm not sure if there is a non-confusing way to bring this back besides just restoring it as-is (which may not be worth having as an option since it merely swaps 1 tap for false positive/2 taps for false negative with 1 tap for false negative/2 taps for false positive). If you always show the card when the answer is not an exact match but have different behavior for a "partially correct"/"near match" vs a "completely wrong" answer, that would just be more confusing.
