### ISSUE TITLE
Beta Expired

### ISSUE THREAD

**Issue by paul-brenner** [davidsansome/tsurukame#610]
Looks like the beta expired. Is it just me? The App Store version still has the bug where the hiragana is cut off so would love either a new App Store version or an update to get the TestFlight build working again.

**Comment by Merman77** [comment]
Same here. Really disappointing since the regular app has not been updated for 10 months. I use Tsurukame several times a day and the beta was the only way I could use it on my iPhone 14 pro Max. I cannot see the answers clearly because the screen cuts them off. Somehow I get the impression further development of this app no longer is a priority of the makers which is such a shame…

**Comment by marciska** [comment]
Same for me, Beta expired.

**Comment by paul-brenner** [comment]
Super generous of the developer to have done so much to this point. I’m wondering if there is anything we can do to help

**Comment by Merman77** [comment]
To me the beta was nearly perfect. It had some issues, like synching in anki mode, but the main problem on my iPhone14 pro was fixed with the beta. Please release the beta as an alpha and you’ll make me a very happy man!

**Comment by UInt2048** [comment]
I'd suggest we stop spamming the thread. It's obvious the beta expired.

@davidsansome Is there a reason you've waited to release build 953 to the App Store? If so, would you be willing to review PR #569?

**Comment by Merman77** [comment]
@davidsansome thank you for the new bet!
