### ISSUE TITLE
Allow background audio

### ISSUE THREAD

**Issue by nzufelt** [davidsansome/tsurukame#625]
When audio is playing in app, background music is temporarily paused. This is a bit jarring for those of us working in loud environments! I believe it’s a small setting within the “play audio” code to allow other audio (e.g. background music) to play in the background while this is playing. I’ll see if I can find it and make a PR.

**Comment by UInt2048** [comment]
Here is the line responsible:

https://github.com/davidsansome/tsurukame/blob/e93e361c209b28e1dbb23f7e5cd888cdf15aa3e0/ios/Audio.swift#L45

As you can see, background audio not using the spokenAudio session mode will continue but a reduced volume, and other audio will be temporarily paused. This is intentional.

**Comment by UInt2048** [comment]
You can read the documentation here if you're interested: https://developer.apple.com/documentation/avfaudio/avaudiosession/categoryoptions

**Comment by charlesprior** [comment]
This could be a setting though. I’m sure many others like myself would prefer not to have the audio ducked/paused. We could have two settings for spoken and non-spoken audio each with the option of pause, duck and do nothing. I’d be happy to implement this if @nzufelt doesn’t want to.

**Comment by davidsansome** [comment]
Thanks for the PR Paul! I think the one setting to interrupt/not interrupt background audio is fine - any more granular settings than that are probably less useful, and might get confusing.
